### PR TITLE
FIX: Typo for gs-printing dependency

### PR DESCRIPTION
**Pull request by emerkle826**
This resolves https://github.com/GeoNode/geoserver-geonode-ext/issues/49

### CODE REVIEW

**Comment by emerkle826** [comment]
@afabiani Please look at issue https://github.com/GeoNode/geoserver-geonode-ext/issues/49 and let me know if I am overlooking something. If it is just a simple typo, removing it should be fine as `gs-printing` is already included.

**Comment by afabiani** [comment]
Hi, nope it is not a typo. Currently the dependencies are both needed.

We have plans to clean up this in the future.

**Comment by ingenieroariel** [comment]
For the record, I have no idea who decided to use 'print next generation'
(printng)  but it has confused developers for years as it really looks like
a typo :)

**Comment by emerkle826** [comment]
Thanks for the clarification @afabiani

**Comment by emerkle826** [comment]
Closing

**Pull request closed without merging**
