### PR TITLE
various improvements for authentication

### PR DESCRIPTION
**Pull request by ingenieroariel**
Documentation, Logging and longer timeout fixes for the Auth client developed by GeoSolutions for WFP.

### CODE REVIEW

**Comment by ischneider** [comment]
It would be nice to clean this up first - sloppy formatting

A bigger blocker is that I don't think that a 300000ms timeout is a very good idea - this could quickly result in a inadvertent DOS attack - appserver threads will be hung on the HTTP call and the pool will be exhausted making the whole thing seem dead. All it would take is one user hitting refresh a few times on a tiled layer map.

Instead, the fix belongs in `layer_acls` or using the db client

**Comment by simboss** [comment]
Ciao Ian,
thanks for the feedback, I did not see it as I was not subscribed for notifications.

We might want to bring this discussion to the ML but let me provide some feedback first.
First of all the change in the DEFAULT_TIMEOUT is NOT the fix, so I will go back to it later.

The problem we (actually Andrea Aime :) to be honest)  replicated and fixed together with the people in WFP Rome was related to wrong usage of Apache HTTP Commons, check the changes in the HTTPClient.java file. Sharing the same multithreaded HTTP connection pool at the GeoServer level when per session cookies are involved and you have multiple users calling GeoServer itself in parallel has proven to be problematic in the past and infact we noticed that in some cases cookies from different users got messed up resulting in intermittent pink tiles and requiring a restart to fix the situation. 

About sloppy formatting, we should have used the GeoTools/GeoServer ones, hence I am not sure how to address this. Please, advise on this.

About the default timeout changes, we can revert this to the original value, however it is normal practice to cache credentials upon login for a certain period of time. 2 secs for GeoNode is an overkill since re-checking means having geonode pushing to GeoServer the entire list of layers and when you have a large number of layers this kills GeoServer performances. 
DDOS prevention should be done with control flow or at the Apache HTTP levels (IMHO :) ) not forcing people to authenticate extremely frequently. 

Anyway, this is not crucial for us hence I am happy with reverting it but the fix for the cookies is crucial as it caused WFP to restart GeoNode a few times a day.

**Comment by capooti** [comment]
Hi all, sorry for getting to this only now, I suffered the same problem suffered by @simboss, lack of notifications.
For some reasons I was sure this PR was already accepted during the sprint, and today I wanted to build it with latest GeoServer 2.7 for packaging it with new GeoNode 2.4, as WFP we are going to migrate to the new version in the next couple of weeks.
@simboss, according to what I am reading here, would it be possible to make the DEFAULT_TIMEOUT configurable? For the rest, I think we definitely need to accept this important PR as it fixed for us a very subtle bug.
Thanks so much!

**Comment by simboss** [comment]
Ciao Paolo,
I would split concerns here. 

1. restore old timeout and discuss the real fix
2. make the timeout configurable

1 and 2 would need to be done in different PR, at least IMHO 

Let's see if we can at least tackle 1 :)

**Comment by ischneider** [comment]
Agreed that 2 seconds is quite short but my guess is that number was arrived to by frustrated developers who "couldn't see" their layers and spent too long tracking down why... (the delay in layer acls getting refreshed by GeoServer).

I still believe strongly the correct configuration for production is to use the database client.

**Comment by simboss** [comment]
Thanks again for the the feedback Ian.

However it is not clear to me how to address it.
As mentioned before the issue is unrelated to the timeout and the timeout value change can be rolled back and discussed separately.

The issue is present in the GeoNode-GeoServer security plugin, see my previous comments, which what people used by default (and in most installations in my experience). 
That said, I am happy to rework as needed the PR as long as the feedback indicates a viable path ahead. IMHO, simply suggesting to use the DB security route when the standard installation use the GeoServer plugin does not solve the issue but provide a workaround.

Looking forward to reading your feedback.

**Comment by capooti** [comment]
hi @ischneider 
could you provide feedback? then @simboss could provide a PR just handling point 1?
while it would be nice to have a PR for point 2 as well.
thanks

**Comment by ischneider** [comment]
I'm +1 for the refactor of `HTTPClient` removing it's use of `MultiThreadedHttpConnectionManager`.

Instead of 'suggesting' the DB client, it probably makes sense to adjust the standard install to provide this as it is several orders of magnitude faster and allows GeoNode to scale to many more layers than the existing approach.

**Comment by etj** [comment]
Hi all, as suggested by Simone in this thread, I'll take care of splitting this PR in two: 
- fix for the auth issue;
- allow configuration for the timeout.

**Pull request closed without merging**
